version: "3"

services:
  master:
    image: spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 172.18.255.255
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
  spark-slave-1:
      image: spark
      command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
      hostname: spark-slave-1
      environment:
        SPARK_CONF_DIR: /conf
        SPARK_PUBLIC_DNS: 172.18.255.255
        SPARK_WORKER_CORES: 1
        SPARK_WORKER_MEMORY: 1g
        SPARK_WORKER_PORT: 8881
        SPARK_WORKER_WEBUI_PORT: 8081
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 7016
        - 8881
      ports:
        - 8081:8081
      links:
        - master
      volumes:
        - ./conf/spark-slave-1:/conf
        - ./data:/tmp/data
  spark-slave-2:
        image: spark
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
        hostname: spark-slave-2
        environment:
          SPARK_CONF_DIR: /conf
          SPARK_PUBLIC_DNS: 172.18.255.255
          SPARK_WORKER_CORES: 1
          SPARK_WORKER_MEMORY: 1g
          SPARK_WORKER_PORT: 8881
          SPARK_WORKER_WEBUI_PORT: 8081
        expose:
          - 7012
          - 7013
          - 7014
          - 7015
          - 7016
          - 8881
        ports:
          - 8082:8081
        links:
          - master
        volumes:
          - ./conf/spark-slave-2:/conf
          - ./data:/tmp/data
  zeppelin:
    image: apache/zeppelin:0.7.3
    expose:
      - 8080
      - 8443
    ports:
      - 8181:8080
      - 8443:8443
  cassandra:
    image: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: CASSANDRA_CLUSTER
    expose:
      - 7199
      - 9042
      - 9160
      - 7000
      - 7001
    ports:
      - 7199:7199
      - 9042:9042
      - 9160:9160
      - 7000:7000
      - 7001:7001
