  #.\spark-submit --master spark://192.168.1.113:7077 --class org.apache.spark.
     #examples.SparkPi ..\examples\jars\spark-examples_2.11-2.1.0.jar 1000v
version: '3'
services:
  master:
    image: spark
    hostname: master
    ports:
     - 4040:4040
     - 8042:8042
     - 7077:7077
     - 8088:8088
     - 8080:8080
    restart: always
    command:  bin/spark-class org.apache.spark.deploy.master.Master -h master
  worker:
    image: spark
    links:
      - master:master
    expose:
      - 8081
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  zeppelin:
    image: apache/zeppelin:0.7.3
    expose:
      - 8080
      - 8443
    ports:
      - 8181:8080
      - 8443:8443
  cassandra:
    image: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: CASSANDRA_CLUSTER
    expose:
      - 7199
      - 9042
      - 9160
      - 7000
      - 7001
    ports:
      - 7199:7199
      - 9042:9042
      - 9160:9160
      - 7000:7000
      - 7001:7001
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
